// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package extensions

import (
	"math/big"
	"testing"

	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/prop"

	fr "github.com/consensys/gnark-crypto/field/koalabear"
)

func genE4() gopter.Gen {
	return gopter.CombineGens(
		genE2(),
		genE2(),
	).Map(func(values []any) E4 {
		return E4{B0: values[0].(E2), B1: values[1].(E2)}
	})
}

// ------------------------------------------------------------
// tests

func TestE4ReceiverIsOperand(t *testing.T) {

	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100

	properties := gopter.NewProperties(parameters)

	genA := genE4()
	genB := genE4()

	properties.Property("[koalabear] Having the receiver as operand (addition) should output the same result", prop.ForAll(
		func(a, b E4) bool {
			var c, d E4
			d.Set(&a)
			c.Add(&a, &b)
			a.Add(&a, &b)
			b.Add(&d, &b)
			return a.Equal(&b) && a.Equal(&c) && b.Equal(&c)
		},
		genA,
		genB,
	))

	properties.Property("[koalabear] Having the receiver as operand (sub) should output the same result", prop.ForAll(
		func(a, b E4) bool {
			var c, d E4
			d.Set(&a)
			c.Sub(&a, &b)
			a.Sub(&a, &b)
			b.Sub(&d, &b)
			return a.Equal(&b) && a.Equal(&c) && b.Equal(&c)
		},
		genA,
		genB,
	))

	properties.Property("[koalabear] Having the receiver as operand (mul) should output the same result", prop.ForAll(
		func(a, b E4) bool {
			var c, d E4
			d.Set(&a)
			c.Mul(&a, &b)
			a.Mul(&a, &b)
			b.Mul(&d, &b)
			return a.Equal(&b) && a.Equal(&c) && b.Equal(&c)
		},
		genA,
		genB,
	))

	properties.Property("[koalabear] Having the receiver as operand (square) should output the same result", prop.ForAll(
		func(a E4) bool {
			var b E4
			b.Square(&a)
			a.Square(&a)
			return a.Equal(&b)
		},
		genA,
	))

	properties.Property("[koalabear] Having the receiver as operand (double) should output the same result", prop.ForAll(
		func(a E4) bool {
			var b E4
			b.Double(&a)
			a.Double(&a)
			return a.Equal(&b)
		},
		genA,
	))

	properties.Property("[koalabear] Having the receiver as operand (Inverse) should output the same result", prop.ForAll(
		func(a E4) bool {
			var b E4
			b.Inverse(&a)
			a.Inverse(&a)
			return a.Equal(&b)
		},
		genA,
	))

	properties.Property("[koalabear] Having the receiver as operand (Conjugate) should output the same result", prop.ForAll(
		func(a E4) bool {
			var b E4
			b.Conjugate(&a)
			a.Conjugate(&a)
			return a.Equal(&b)
		},
		genA,
	))

	properties.Property("[koalabear] Having the receiver as operand (Sqrt) should output the same result", prop.ForAll(
		func(a E4) bool {
			var b, c, d, s E4

			s.Square(&a)
			a.Set(&s)
			b.Set(&s)

			a.Sqrt(&a)
			b.Sqrt(&b)

			c.Square(&a)
			d.Square(&b)
			return c.Equal(&d)
		},
		genA,
	))

	properties.TestingRun(t, gopter.ConsoleReporter(false))
}

func TestE4Ops(t *testing.T) {

	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100

	properties := gopter.NewProperties(parameters)

	genA := genE4()
	genB := genE4()

	properties.Property("[koalabear] sub & add should leave an element invariant", prop.ForAll(
		func(a, b E4) bool {
			var c E4
			c.Set(&a)
			c.Add(&c, &b).Sub(&c, &b)
			return c.Equal(&a)
		},
		genA,
		genB,
	))

	properties.Property("[koalabear] mul & inverse should leave an element invariant", prop.ForAll(
		func(a, b E4) bool {
			var c, d E4
			d.Inverse(&b)
			c.Set(&a)
			c.Mul(&c, &b).Mul(&c, &d)
			return c.Equal(&a)
		},
		genA,
		genB,
	))

	properties.Property("[koalabear] BatchInvertE4 should output the same result as Inverse", prop.ForAll(
		func(a, b, c E4) bool {

			batch := BatchInvertE4([]E4{a, b, c})
			a.Inverse(&a)
			b.Inverse(&b)
			c.Inverse(&c)
			return a.Equal(&batch[0]) && b.Equal(&batch[1]) && c.Equal(&batch[2])
		},
		genA,
		genA,
		genB,
	))

	properties.Property("[koalabear] inverse twice should leave an element invariant", prop.ForAll(
		func(a E4) bool {
			var b E4
			b.Inverse(&a).Inverse(&b)
			return a.Equal(&b)
		},
		genA,
	))

	properties.Property("[koalabear] square and mul should output the same result", prop.ForAll(
		func(a E4) bool {
			var b, c E4
			b.Mul(&a, &a)
			c.Square(&a)
			return b.Equal(&c)
		},
		genA,
	))

	properties.Property("[koalabear] Legendre on square should output 1", prop.ForAll(
		func(a E4) bool {
			var b E4
			b.Square(&a)
			c := b.Legendre()
			return c == 1
		},
		genA,
	))

	properties.Property("[koalabear] square(sqrt) should leave an element invariant", prop.ForAll(
		func(a E4) bool {
			var b, c, d, e E4
			b.Square(&a)
			c.Sqrt(&b)
			d.Square(&c)
			e.Neg(&a)
			return (c.Equal(&a) || c.Equal(&e)) && d.Equal(&b)
		},
		genA,
	))

	properties.TestingRun(t, gopter.ConsoleReporter(false))
}

func TestE4Exp(t *testing.T) {
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100

	properties := gopter.NewProperties(parameters)
	genA := genE4()

	properties.Property("[koalabear] Exp(x, 0) should return one", prop.ForAll(
		func(a E4) bool {
			var res E4
			var one E4
			one.SetOne()
			res.Exp(a, big.NewInt(0))
			return res.Equal(&one)
		},
		genA,
	))

	properties.Property("[koalabear] Exp(x, 1) should return x", prop.ForAll(
		func(a E4) bool {
			var res E4
			res.Exp(a, big.NewInt(1))
			return res.Equal(&a)
		},
		genA,
	))

	properties.Property("[koalabear] Exp(x, 2) should return x squared", prop.ForAll(
		func(a E4) bool {
			var res, sq E4
			res.Exp(a, big.NewInt(2))
			sq.Square(&a)
			return res.Equal(&sq)
		},
		genA,
	))

	properties.Property("[koalabear] Exp(x, k) should match repeated multiplication", prop.ForAll(
		func(a E4) bool {
			var res, mul E4
			k := int64(0b101101) // 45
			res.Exp(a, big.NewInt(k))
			mul.SetOne()
			for range k {
				mul.Mul(&mul, &a)
			}
			return res.Equal(&mul)
		},
		genA,
	))

	properties.TestingRun(t, gopter.ConsoleReporter(false))
}

// ------------------------------------------------------------
// benches

func BenchmarkE4Add(b *testing.B) {
	var a, c E4
	a.MustSetRandom()
	c.MustSetRandom()
	b.ResetTimer()
	for range b.N {
		a.Add(&a, &c)
	}
}

func BenchmarkE4Sub(b *testing.B) {
	var a, c E4
	a.MustSetRandom()
	c.MustSetRandom()
	b.ResetTimer()
	for range b.N {
		a.Sub(&a, &c)
	}
}

func BenchmarkE4Mul(b *testing.B) {
	var a, c E4
	a.MustSetRandom()
	c.MustSetRandom()
	b.ResetTimer()
	for range b.N {
		a.Mul(&a, &c)
	}
}

func BenchmarkE4MulByElement(b *testing.B) {
	var a E4
	var c fr.Element
	_, _ = a.SetRandom()
	_, _ = c.SetRandom()
	b.ResetTimer()
	for range b.N {
		a.MulByElement(&a, &c)
	}
}

func BenchmarkE4Square(b *testing.B) {
	var a E4
	a.MustSetRandom()
	b.ResetTimer()
	for range b.N {
		a.Square(&a)
	}
}

func BenchmarkE4Sqrt(b *testing.B) {
	var a, c E4
	a.MustSetRandom()
	a.Square(&a)
	b.ResetTimer()
	for range b.N {
		c.Sqrt(&a)
	}
}

func BenchmarkE4Inverse(b *testing.B) {
	var a E4
	a.MustSetRandom()
	b.ResetTimer()
	for range b.N {
		a.Inverse(&a)
	}
}

func BenchmarkE4Conjugate(b *testing.B) {
	var a E4
	a.MustSetRandom()
	b.ResetTimer()
	for range b.N {
		a.Conjugate(&a)
	}
}
